# Configuration file
# #################
# How to setup:
# 1. Follow the instructions at https://goo.gl/ESlSaR to setup mysql backend on PEX
# 2. Fill the options below with your database connection details
# 3. Start up the server and enjoy!
#
# If you require assistance contact me:
#   EMAIL: nostrumg@gmail.com SKYPE: gui_poseidon

# Choose your permissions system. (ALL UPPERCASE AS ON THE LEFT LIST)
# Supported systems:
# PEX - PermissionsEx
# SEXYPEX - SexyPex

permissionsSystem: PEX

mysql:

  # MySQL Hostname
  hostname: localhost

  # MySQL Username
  user: root

  # MySQL Password
  pass: ''

  # MySQL Database
  db: database

  # MySQL Port
  port: '3306'

# Minutes between updating/reloading permissions automatically
updateInterval: 120



# Optional settings for each permissions system. Only edit the settings under the permissions system you are using

# PermissionsEx settings
pex:
  tables:

    # PEX MySQL table names
    # If you didn't change the default values on pex's config for 'aliases' leave as it is
    permissions: permissions
    permissionsInheritance: permissions_inheritance


# SexyPex settings
sexypex:
  tables:

    # SEXYPEX MySQL table names
    # If you didn't change the default values on permissionsex's config for 'aliases' leave as it is
    permissions: permissions
    permissionsInheritance: permissions_inheritance